credentials:
  usernames:
    amazuz:
      email: albertmazuz@gmail.com
      name: Albert Mazuz
      password: $2b$12$1zpBRv5fRY7iG8QJ3EOiy.zEJ8Z7fo2GoqiMUa7M7TL0Q0EVNaMii # To be replaced with hashed password
    jmachado:
      email: jessica.machado91@gmail.com
      name: Jessica Machado
      password: $2b$12$FPDZ5ftubzSHwW.Fea935.Xxgi4ukB379Gmzz/cdpTlr2NmF56zrS # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: seila # Must be string
  name: cookiename
preauthorized:
  emails:
  - albert.mazuz@gmail

  ###https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/